## Setup
1. create conda env
- `conda create -n pandas_demos_env`

2. install pip
- `conda install pip`
- Pip & conda are both package managers, but pip provides latest version of Python packages and is the standard choice for virtual environments.
    -   It also has a larger package index where most python related packages are readily available.
3. install pandas through pip 
- `pip install pandas`

## What is pandas?
Pandas is a popular open-source Python library widely used for data manipulation and analysis. Since python is the computing language for DATA, pandas is one of the most popular libraries. It provides powerful data structures and data analysis tools that make it easier to work with structured data. It provides a convenient and efficient way to handle, manipulate, and analyze data in Python, making it an essential tool for any data-related tasks. Excel is limited compared to what python offers in flexibility and size

### Key features: 
1. **Series**: A Series is a one-dimensional labeled array in pandas. It is used to represent a single column of data in a DataFrame. Series can hold data of any data type, including numeric, string, and datetime.

2. **DataFrame**: The DataFrame is the primary data structure in pandas. It is a two-dimensional labeled data structure, similar to a spreadsheet or SQL table. DataFrames allow you to store and manipulate data with rows and columns, making it easy to perform various data operations.

3. **Performance**: Pandas is designed to handle large datasets efficiently. It optimizes operations and uses NumPy under the hood to ensure fast and memory-efficient computations.

4. **Data Cleaning**: Pandas offers a variety of functions to handle missing data, duplicate records, and outliers. It allows you to drop or fill missing values, remove duplicates, and perform data imputation efficiently.

5. **Data Transformation**: Pandas provides powerful data transformation capabilities, such as filtering, sorting, grouping, and aggregating data. These operations help in summarizing and analyzing data effectively.

6. **Data Input and Output**: Pandas supports reading and writing data from various file formats, including CSV, Excel, SQL databases, and more. This functionality facilitates the easy import and export of data to and from different sources. 

7. **Time Series Data**: Pandas offers specialized data structures and functions for handling time series data. It can handle time-based indexing, resampling, and window-based operations efficiently.

8. **Data Visualization**: Although pandas itself does not provide data visualization tools, it integrates seamlessly with popular visualization libraries like Matplotlib and Seaborn. This combination allows you to create insightful visualizations based on your data.

In [2]:
# Import the package
# Give the package the alias pd
import pandas as pd
import numpy as np

# Data Structures (Series & Dataframe)

The main components of pandas are the series and dataframe.

Series - a labeled one-dimensional array, acting as a basic component of Pandas data structures. It stores various data types, has an index for easy data access, and supports efficient operations like indexing and mathematical computations. Series are versatile, used independently or as DataFrame columns, and are crucial for data analysis and manipulation tasks in Python.

Dataframe - a two-dimensional data structure at the core of Pandas. ***It resembles a spreadsheet or SQL table, allowing data to be organized in rows and columnsIt organizes data like a table, with rows and columns.*** Each column can hold different data types, like numbers, strings, or dates. The DataFrame offers powerful tools for data manipulation, filtering, sorting, and analysis. It also seamlessly integrates with data visualization libraries, making it convenient to create informative plots. Thanks to its flexibility and user-friendliness, the Pandas DataFrame is a vital tool for data analysis and exploration in Python.

> TLDR: A Series is essentially a column, and a DataFrame is a multi-dimensional table made up of a collection of Series.

In [4]:
# Creating a series 
data_dict = {'Name': ['John', 'Emma', 'David', 'Sophia', 'Michael', 'Carla']}
series_dict = pd.Series(data_dict)
print(type(series_dict))
display(series_dict)

<class 'pandas.core.series.Series'>

Name    [John, Emma, David, Sophia, Michael, Carla]
dtype: object

In [20]:
# Creating a dataframe
data = {'Name': ['John', 'Emma', 'David', 'Sophia', 'Michael', 'Carla'],
        'Age': [28, 32, 45, 36, 40, 39],
        'City': ['New York', 'Paris', 'London', 'Tokyo', 'Sydney', 'New York'],
        'Height': [176, 155, 190, 142, 183, 179],
        'Employed': [True, True, True, False, False, True]
}
df = pd.DataFrame(data)
df_copy = df.copy()

In [10]:
# Displaying the DataFrame 
display(df)

      Name  Age      City  Height  Employed
0     John   28  New York     176      True
1     Emma   32     Paris     155      True
2    David   45    London     190      True
3   Sophia   36     Tokyo     142     False
4  Michael   40    Sydney     183     False
5    Carla   39  New York     179      True

### Basic Dataframe Operations

In [27]:
# Basic DataFrame operations
print("Basic DataFrame operations:")
print("Shape:", df.shape) # prints the df's rows by columns
print("Column names:", df.columns) # prints out the df's column names
print("Data types:", df.dtypes) # prints out the df's column datatypes

Basic DataFrame operations:
Shape: (6, 5)
Column names: Index(['Name', 'Age', 'City', 'Height', 'Employed'], dtype='object')
Data types: Name        object
Age          int64
City        object
Height       int64
Employed      bool
dtype: object

### Dtypes
Pandas dtypes specify the data types associated with the values in a DataFrame or Series. Each column in a DataFrame can have its own data type, which defines the kind of data that can be stored in that column.

1. Numeric data types:

    - int64: 64-bit integer, represents whole numbers.
    - float64: 64-bit floating-point number, represents decimal numbers.


2. Text data types:
    - object: Represents strings or mixed data types. When a column contains different types of data (e.g., strings and numbers), Pandas assigns the object dtype to that column.


3. DateTime data types:
    - datetime64: Represents date and time information with nanosecond precision.


4. Boolean data type:
    - bool: Represents Boolean values (True or False).


5. Categorical data type:
    - category: Represents a categorical variable with a fixed set of unique values. Categorical data is memory-efficient and allows for faster data processing.

Understanding and managing dtypes is crucial for effective data analysis, memory optimization, and performing operations on the data.

You can change the data types of columns using `astype()` method.

In [11]:
df['Height'] = df['Height'].astype('float64')

print(df.dtypes)

Name         object
Age         float64
City         object
Height      float64
Employed       bool
dtype: object

### Overview of Dataframe

`info()` method: 
- The info() method is used to display a concise summary of a DataFrame, including the number of non-null values and data types of each column.
- It gives an overview of the DataFrame, showing important information like the number of rows, the number of non-null values in each column, and the data types of the columns.
- The method is particularly useful to quickly assess the completeness and data types of your dataset.

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Age       6 non-null      int64
 2   City      6 non-null      object
 3   Height    6 non-null      float64
 4   Employed  6 non-null      bool
dtypes: bool(1), float64(1), int64(1), object(2)
memory usage: 330.0+ bytes

`describe()` method: 
- The describe() method is used to generate descriptive statistics of the numerical columns in a DataFrame.
- It provides a summary of central tendency, dispersion, and shape of the distribution of each numerical column.

In [30]:
print(df.describe())
# count - The number of not-empty values.
# mean - The average (mean) value.
# std - The standard deviation.
# min - the minimum value.
# 25% - The 25% percentile*.
# 50% - The 50% percentile*.
# 75% - The 75% percentile*.
# max - the maximum value.

             Age      Height
count   6.000000    6.000000
mean   36.666667  170.833333
std     6.055301   18.389308
min    28.000000  142.000000
25%    33.000000  160.250000
50%    37.500000  177.500000
75%    39.750000  182.000000
max    45.000000  190.000000

### Aggregating Data with Pandas

Aggregating data involves summarizing information within your DataFrame to gain insights. Pandas provides several aggregation functions that you can use to calculate statistics like the mean, minimum, maximum, and more.

#### Calculating Mean
The .mean() function calculates the average of a column or DataFrame. Let's find the average age and grade of our friends:

In [31]:
# Calculate the average age
average_age = df['Age'].mean()

# Calculate the average grade
average_height = df['Height'].mean()

print("Average Age:", average_age)
print("Average Height:", average_height)

Average Age: 36.666666666666664
Average Height: 170.83333333333334

#### Finding Minimum and Maximum Values
You can use .min() and .max() to find the minimum and maximum values in a column. For example, let's find the youngest and oldest friend in our DataFrame:

In [32]:
# Find the youngest friend
youngest_age = df['Age'].min()

# Find the oldest friend
oldest_age = df['Age'].max()

print("Youngest Age:", youngest_age)
print("Oldest Age:", oldest_age)

Youngest Age: 28
Oldest Age: 45

#### Counting Values
To count the number of occurrences of unique values in a column, use .value_counts(). Let's count how many friends live in each city:

In [33]:
# Count the number of friends in each city
city_counts = df['City'].value_counts()

print("City Counts:")
print(city_counts)

City Counts:
City
New York    2
Paris       1
London      1
Tokyo       1
Sydney      1
Name: count, dtype: int64

# Adding and deleting columns

**Adding Columns:**

- To add a new column to a DataFrame, you can simply assign values to a new column name using the assignment operator (=).
- If the specified column name does not exist, Pandas will create a new column with that name and assign the values to it. If the column already exists, the values in the existing column will be replaced with the new values.

In [13]:
df['Profession'] = ['Engineer', 'Artist', 'Doctor', 'Teacher', 'Lawyer', 'Manager'] 
# length of new columns must match existing dataframe
display(df)
new_df = df.pop('Profession')
display(new_df)

      Name   Age      City  Height  Employed Profession
0     John  28.0  New York   176.0      True   Engineer
1     Emma  32.0     Paris   155.0      True     Artist
2    David  45.0    London   190.0      True     Doctor
3   Sophia  36.0     Tokyo   142.0     False    Teacher
4  Michael  40.0    Sydney   183.0     False     Lawyer
5    Carla  39.0  New York   179.0      True    Manager

0    Engineer
1      Artist
2      Doctor
3     Teacher
4      Lawyer
5     Manager
Name: Profession, dtype: object

**Removing Columns:**

- To remove a column from a DataFrame, you can use the del keyword or the drop() method.
- Using the del keyword: You can delete a column using the del keyword followed by the DataFrame name and the column name within square brackets.
- Using the drop() method: The drop() method allows you to remove columns by specifying the column name and setting the axis parameter to 1. By default, the drop() method returns a new DataFrame without the specified column. If you want to modify the original DataFrame in place, you can set the inplace parameter to True.

In [19]:
df['Profession'] = ['Engineer', 'Artist', 'Doctor', 'Teacher', 'Lawyer', 'Manager'] 
display(df)

df = df.drop(1, axis=0)
#del df['Profession']
display(df)

      Name   Age      City  Height  Employed Profession
0     John  28.0  New York   176.0      True   Engineer
1     Emma  32.0     Paris   155.0      True     Artist
2    David  45.0    London   190.0      True     Doctor
3   Sophia  36.0     Tokyo   142.0     False    Teacher
4  Michael  40.0    Sydney   183.0     False     Lawyer
5    Carla  39.0  New York   179.0      True    Manager

      Name   Age      City  Height  Employed Profession
0     John  28.0  New York   176.0      True   Engineer
2    David  45.0    London   190.0      True     Doctor
3   Sophia  36.0     Tokyo   142.0     False    Teacher
4  Michael  40.0    Sydney   183.0     False     Lawyer
5    Carla  39.0  New York   179.0      True    Manager

In [36]:
# re-adding column
df['Profession'] = ['Engineer', 'Artist', 'Doctor', 'Teacher', 'Lawyer', 'Manager'] 
display(df)

df.drop('Profession', axis=1, inplace=True)
display(df)

      Name  Age      City  Height  Employed Profession
0     John   28  New York   176.0      True   Engineer
1     Emma   32     Paris   155.0      True     Artist
2    David   45    London   190.0      True     Doctor
3   Sophia   36     Tokyo   142.0     False    Teacher
4  Michael   40    Sydney   183.0     False     Lawyer
5    Carla   39  New York   179.0      True    Manager

      Name  Age      City  Height  Employed
0     John   28  New York   176.0      True
1     Emma   32     Paris   155.0      True
2    David   45    London   190.0      True
3   Sophia   36     Tokyo   142.0     False
4  Michael   40    Sydney   183.0     False
5    Carla   39  New York   179.0      True

## Accessing data

In [23]:
print("Accessing data:")
print(df.head()) # prints first 3 entries
print(df.tail(3)) # prints last 3 entries
print(df.sample(3))

Accessing data:
      Name  Age      City  Height  Employed
0     John   28  New York     176      True
1     Emma   32     Paris     155      True
2    David   45    London     190      True
3   Sophia   36     Tokyo     142     False
4  Michael   40    Sydney     183     False
      Name  Age      City  Height  Employed
3   Sophia   36     Tokyo     142     False
4  Michael   40    Sydney     183     False
5    Carla   39  New York     179      True
     Name  Age      City  Height  Employed
0    John   28  New York     176      True
1    Emma   32     Paris     155      True
3  Sophia   36     Tokyo     142     False

In [38]:
print('get a single column')
# Single bracket notation returns a Pandas series
print(df['City'])
print('-----------')
print('get multiple columns')
# Double bracket returns a Pandas dataframe.
print(df[['City', 'Age']])
print('-----------')

get a single column
0    New York
1       Paris
2      London
3       Tokyo
4      Sydney
5    New York
Name: City, dtype: object
-----------
get multiple columns
       City  Age
0  New York   28
1     Paris   32
2    London   45
3     Tokyo   36
4    Sydney   40
5  New York   39
-----------

### Filtering Data with Conditional Selection

You can use conditional expressions to filter data based on specific conditions. For example, you can filter rows where a particular column has values greater than a certain threshold or where a text column contains a specific substring.
> Conditional selection is often done using comparison operators (>, <, ==, !=, etc.) combined with logical operators (& for AND, | for OR, ~ for NOT).

Pandas will return a DataFrame containing only the rows that satisfy the given conditions.

In [2]:
data = {
    'Name': ['John', 'Emma', 'David', 'Sophia', 'Michael', 'Carla'],
    'Age': [28, 32, 45, 36, 40, 39],
    'City': ['New York', 'Paris', 'London', 'Tokyo', 'Sydney', 'New York'],
    'Height': [176, 155, 190, 142, 183, 179],
    'Employed': [True, True, True, False, False, True]
}
# Notice how before the index has been ints (0-5), now with the index arg, the index is letters.
# 
df = pd.DataFrame(data, index=['A', 'B', 'C', 'D', 'E', 'F'])

In [3]:
bool_mask = df['Age'] > 35
filtered_df = df[bool_mask]
print(filtered_df)

      Name  Age      City  Height  Employed
C    David   45    London     190      True
D   Sophia   36     Tokyo     142     False
E  Michael   40    Sydney     183     False
F    Carla   39  New York     179      True

In [9]:
display(df)
filtered_height_df = df[df['Height'] < 183]
display(filtered_height_df)

      Name  Age      City  Height  Employed
0     John   28  New York     176      True
1     Emma   32     Paris     155      True
2    David   45    London     190      True
3   Sophia   36     Tokyo     142     False
4  Michael   40    Sydney     183     False
5    Carla   39  New York     179      True

     Name  Age      City  Height  Employed
0    John   28  New York     176      True
1    Emma   32     Paris     155      True
3  Sophia   36     Tokyo     142     False
5   Carla   39  New York     179      True

In [42]:
# Select rows where 'Name' contains string 'o'
filtered_df_str = df[df['Name'].str.contains('o')]
print(filtered_df_str)

     Name  Age      City  Height  Employed
A    John   28  New York     176      True
D  Sophia   36     Tokyo     142     False

In [25]:
# Combining Multiple Conditions:
filtered_combo_df = df[(df['Age'] > 35) & (df['City'] != 'London')]
print(filtered_combo_df)

      Name  Age      City  Height  Employed
3   Sophia   36     Tokyo     142     False
4  Michael   40    Sydney     183     False
5    Carla   39  New York     179      True

# Sorting the DataFrame

In Pandas, the `.sort_values()` method is used to sort a DataFrame based on the values in one or more columns. It arranges the rows of the DataFrame in ascending or descending order, depending on the specified sorting criteria.

In [27]:
sorted_df = df.sort_values('City', ascending=False)
display(sorted_df)

      Name  Age      City  Height  Employed
3   Sophia   36     Tokyo     142     False
4  Michael   40    Sydney     183     False
1     Emma   32     Paris     155      True
0     John   28  New York     176      True
5    Carla   39  New York     179      True
2    David   45    London     190      True

**Sorting by Multiple Columns:**
You can also sort a DataFrame based on multiple columns by passing a list of column names to the by parameter. The DataFrame will be first sorted by the first column in the list, and if there are ties, it will be sorted by the second column, and so on.

In [29]:
sorted_df2 = df.sort_values(by=['City', 'Age'], ascending=[True, True])
display(sorted_df2)

      Name  Age      City  Height  Employed
2    David   45    London     190      True
0     John   28  New York     176      True
5    Carla   39  New York     179      True
1     Emma   32     Paris     155      True
4  Michael   40    Sydney     183     False
3   Sophia   36     Tokyo     142     False

# Handling missing values

We must distinguish between None, 0 and NaN here: 
- None has the data type 'NoneType' and is therefore a value, and we can use this as a placeholder before adding values
- 0 is an integer, and therefore a value, this shows that we have a response in the cell, but the response is 0
- NaN stands for 'Not a Number' and so denotes a MISSING value, although it has the type float

In [31]:
data_with_nan = {
    'Name': ['John', 'Emma', 'David', None, 'Michael'],
    'Age': [28, 32, None, 36, 40],
    'City': ['New York', 'Paris', 'London', 'Tokyo', np.NaN]
}

In [34]:
df_nan = pd.DataFrame(data_with_nan)
display(df_nan)

      Name   Age      City
0     John  28.0  New York
1     Emma  32.0     Paris
2    David   NaN    London
3     None  36.0     Tokyo
4  Michael  40.0       NaN

In [48]:
print(df_nan.isnull().sum())

Name    1
Age     1
City    1
dtype: int64

`.dropna()` method:

The .dropna() method is used to remove missing values (NaN) from a DataFrame. It drops rows or columns that contain at least one NaN value, depending on the axis parameter.

In [36]:
df_dropped = df_nan.dropna(axis=0)
df_dropped

   Name   Age      City
0  John  28.0  New York
1  Emma  32.0     Paris

`.fillna()` method:

The .fillna() method is used to fill missing values (NaN) in a DataFrame with specified values or by using specific filling strategies.

In [50]:
df_fill = df_nan.fillna({'Name': 'Unknown', 'Age': 0, 'City': 'Unknown'})
df_fill

      Name   Age      City
0     John  28.0  New York
1     Emma  32.0     Paris
2    David   0.0    London
3  Unknown  36.0     Tokyo
4  Michael  40.0   Unknown