### Q1. Create a DataFrame with three columns: 'Name', 'Age', and 'City', containing information about three of your friends.

In [38]:
#code
import pandas as pd

data = { "Name": ["Jim", "Mary", "Lucy", "John", "Sam", "Will", "Will"],
         "Age": [45, 26, 15, 70, 53, 83, 72],
         "City": ["Los Angeles", "London", "Paris", "London", None, "London", "Paris"]
}

df = pd.DataFrame(data)
display(df)

   Name  Age         City
0   Jim   45  Los Angeles
1  Mary   26       London
2  Lucy   15        Paris
3  John   70       London
4   Sam   53         None
5  Will   83       London
6  Will   72        Paris

### Q2. a) Display the first 5 rows of your DataFrame.
### b) How can you display the last 3 rows of your DataFrame?

In [8]:
#code
display(df.tail(3))

   Name  Age    City
3  John   70  London
4   Sam   53   Paris
5  Will   83  London

### Q3. a) Extract and print the 'Age' column from your DataFrame. 
### b) Extract and print the 'Name' and 'City' columns from your DataFrame.

In [14]:
#code
display(df[["Age"]])

   Age
0   25
1   26
2   30
3   70
4   53
5   83

In [13]:
display(df[["Name", "City"]])

   Name         City
0   Jim  Los Angeles
1  Mary       London
2  Lucy        Paris
3  John       London
4   Sam        Paris
5  Will       London

### Q4. a) Add a new column called 'Country' to your DataFrame and assign a country name to each friend. 
### b) Calculate the average age of your friends and print it.

In [16]:
#code
df["Country"] = ["USA", "UK", "France", "UK", "France", "UK"]
display(df)

   Name  Age         City Country
0   Jim   25  Los Angeles     USA
1  Mary   26       London      UK
2  Lucy   30        Paris  France
3  John   70       London      UK
4   Sam   53        Paris  France
5  Will   83       London      UK

In [17]:
age_average = df["Age"].mean()
print(age_average)

47.833333333333336

### Q5. a) Create a new DataFrame containing only friends who are older than 25 by filtering the previous df. 
### b) Create another DataFrame containing only friends who live in a specific city (e.g., 'New York').

In [20]:
#code
copy_df = df[df["Age"] > 25]
display(copy_df)

   Name  Age    City
1  Mary   26  London
2  Lucy   30   Paris
3  John   70  London
4   Sam   53   Paris
5  Will   83  London

### Q6. a) Simulate missing data in one of the columns (e.g., set the 'City' of one friend to None) and then remove that row from the DataFrame.
### b) Create a DataFrame with duplicate rows and remove the duplicates. (hint look into this function: https://pandas.pydata.org/docs/reference/api/pandas.Index.drop_duplicates.html#pandas-index-drop-duplicates and try it out!)

In [21]:
copy_df_2 = df[df["City"] == "London"]
display(copy_df_2)

   Name  Age    City
1  Mary   26  London
3  John   70  London
5  Will   83  London

In [28]:
#code
df_none = df["City"].dropna(axis=0)
display(df_none)

0    Los Angeles
1         London
2          Paris
3         London
5         London
Name: City, dtype: object

In [32]:
df_drop_duplicates = df.drop_duplicates()
display(df_drop_duplicates)

   Name  Age         City
0   Jim   24  Los Angeles
1  Mary   26       London
2  Lucy   30        Paris
3  John   70       London
4   Sam   53         None
5  Will   83       London
6  Will   83        Paris

### Q7. a) Sort your DataFrame by 'Age' in ascending order.
### b) Sort your DataFrame by 'Name' in alphabetical order.

In [39]:
#code
df = df.sort_values(["Age", "Name"], ascending=[True, True])
display(df)

   Name  Age         City
2  Lucy   15        Paris
1  Mary   26       London
0   Jim   45  Los Angeles
4   Sam   53         None
3  John   70       London
6  Will   72        Paris
5  Will   83       London

In [36]:
df = df.sort_values(["Name"], ascending=True)
display(df)

   Name  Age         City
0   Jim   24  Los Angeles
3  John   70       London
2  Lucy   30        Paris
1  Mary   26       London
4   Sam   53         None
5  Will   83       London
6  Will   83        Paris